### ISSUE TITLE
Unable to connect to NextCloud (Webdav) in Brave

### ISSUE THREAD

**Issue by stevenhorner** [buttercup/buttercup-browser-extension#205]
Trying to setup the Chrome Extension in Brave Browser, but when trying to add my Nextcloud as the password archive source. I receive an error "Failed connecting to 'nextcloud' resource as can be seen in the attached image.

![buttercup2](https://user-images.githubusercontent.com/1365297/49580938-2ea00280-f948-11e8-9b04-c6403a5acda7.jpg)

Brave Version: Version 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
OS: Windows 10
Nextcloud: 13.04

Brave uses the Chromium engine and all other extensions I've tried worked fine, also my Nextcloud is working correctly and the Buttercup Mobile app works fine with the archive hosted in my Nextcloud.

**Comment by perry-mitchell** [comment]
Hi @stevenhorner: This is most likely a CORS issue. We have something to try and bypass this - #197 - But it's a complex issue and we don't want to forego security if we can avoid doing so.

You can also see here that we've been trying repeatedly to get support for web-based WebDAV access: https://github.com/nextcloud/server/issues/3131#issuecomment-444227211

Sadly I don't see this as being a quick fix. Mobile/Desktop apps work because they request from the **NodeJS side**, which does not used web-based requests that are restricted by CORS. We have no choice on the matter when in a browser environment.

**Comment by stevenhorner** [comment]
Looks like they may be trying to get it working in Nextcloud looking at your linked comment, fingers crossed.

**Comment by frouty** [comment]
Hi,
For me 
"""Failed connecting to 'nextcloud' resource
A connection attempt to 'https://MYiPFREENAS' has failed: Connection failed to WebDAV service: https://MyIPFREENAS/remote.php/webdav
"""
with chrome web-extension :
Chromium
Version 73.0.3683.75 (Developer Build) built on Debian 9.8, running on Debian 9.9 (64-bit)
Buttercup 2.7.0
Browser extension for Buttercup
------
Same for the client
""connection to "https://MyIPFREENAS/remote.php/webdav". Please check your credential and try again. 
"""
Buttercup v1.15.0
------
But it works with firefox 
Firefox quantum : 60.7.2esr (64-bit)
web extention Buttercup 2.7.0 
-------
Nextcloud 14
-------
If I can help. Will be me pleasure.
Thanks.
L.FRANCOis

**Comment by perry-mitchell** [comment]
I'm sorry to be the bearer of bad news, but we've [previously deprecated](https://medium.com/@buttercup_pw/were-deprecating-owncloud-and-nextcloud-connections-but-it-s-still-possible-to-use-them-with-abeec4d30101) ownCloud/Nextcloud connections due to CORS issues. We're still supporting WebDAV (and backing it 100%), so you'll always be able to connect to ownCloud and Nextcloud (assuming they continue supporting WebDAV), but we won't be handling connection issues.

We _will_ be accepting issues that may improve connectivity with these services, but not bug reports relating only to the connection to them. We hope you understand - we simply do not have the bandwidth to support such requirements. It's entirely up to you (as a consumer) and Nextcloud/ownCloud (as providers).

**Comment by perry-mitchell** [comment]
^ All that being said, I can recommend checking the network panel (and developer console) while connecting, to see what the actual issue is. If it is indeed a CORS issue, you can fix this by editing the webserver config of your host and specifying that all requests return extra headers:
 * `Access-Control-Allow-Origin: *`
 * `Access-Control-Allow-Credentials: true`
 * `Access-Control-Allow-Methods: GET, POST, PUT, OPTIONS, PROPFIND, DELETE`
 * `Access-Control-Allow-Headers: Content-Type, Content-Length`
