### ISSUE TITLE
question: release notes and/or git tags for 2.1.2

### ISSUE THREAD

**Issue by jokeyrhyme** [buttercup/buttercup-browser-extension#208]
Howdie!

I noticed that the browser extension got updated to 2.1.2:
![image](https://user-images.githubusercontent.com/479816/49719718-11559600-fcb2-11e8-8d76-d04076f487ec.png)

I noticed that CHANGELOG.md has 2.1.1, and there's a git tag for 2.1.1, but there's nothing for 2.1.2

Is this a legitimate version, or have I been compromised in some way?

Cheers!

**Comment by perry-mitchell** [comment]
Ah, I must have forgotten to push! Sorry. No security issue. We have separate accounts and very carefully protect our publishing pipeline for our products.

That being said, the publishing of the extension needs polish so that I don't forget to push the tag/changelog. Apologies! I'll leave this open as a reminder.
