### ISSUE TITLE
[Bug] Popup menu broken on some websites (styles)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#217]
See the following (domainhotelli.fi):

![image](https://user-images.githubusercontent.com/3869469/50711351-a57b0900-1076-11e9-972f-2ea6462124fa.png)

**Comment by ttamminen** [comment]
I am (quite) confident that the issue is caused by React-Virtualized which was added [in this PR](https://github.com/buttercup/buttercup-browser-extension/pull/213).

I think the row height should be determined by the row state (is is just an entry on the list or expanded to a form), instead of giving a fixed number. The problem can be reproduced by giving a search filter that will give only one result and then hitting the "..."-button. 

```
                    <List
                        width={width}
                        height={height}
                        rowCount={entries.length}
                        rowHeight={66} // <- this is the problem.
                        rowRenderer={this.rowRenderer}
                        overscanRowCount={10}
                    />
```

rowHeight takes either a number or function, I'll try fix be giving it a bit of context what it should render.

**Comment by perry-mitchell** [comment]
Not sure that I can reproduce the original image any more, but I've noticed other oddities - it seems that the sizing of each box is off:

![image](https://user-images.githubusercontent.com/3869469/50856464-74ab1480-1393-11e9-9f8f-a0a91b851559.png)

And expanding the content now overlaps:

![image](https://user-images.githubusercontent.com/3869469/50856523-9dcba500-1393-11e9-9362-5a2b73238fe9.png)

**Comment by ttamminen** [comment]
Try typing "Amazon AWS" so that you will get only one search result, then try hitting the "..." -button.
