### ISSUE TITLE
Login fields not detected

### ISSUE THREAD

**Issue by daeh** [buttercup/buttercup-browser-extension#265]
Buttercup seems to detect about 80-90% of login fields whereas the browsers I use are basically at ceiling. I presume this is a known issue? Might it make sense to provide an easy way for people to submit websites where Buttercup fails to recognize login/password fields?

**Comment by perry-mitchell** [comment]
Well to be honest, website input detection is hard. It’d be higher if everyone followed standards but of course that’s not the case. I’d love to see a user-sourcing option for submitting website configs. Not sure what that’d look like but I suspect it’d require a hosted service, which is a bit of work. Not ruling that out, but I don’t see another straightforward option right now.

Definitely open for ideas and speculations here..

**Comment by daeh** [comment]
I hear that. I'm hoping someone smarter than me is going to figure out a general solution. How do browsers manage it? Every browser I use regularly (Chrome, Brave, Firefox, Safari) seem to detect the relevant fields (at least password input) effectively 100% of the time. Is there any way to let the browser handle the detection?

**Comment by perry-mitchell** [comment]
> Is there any way to let the browser handle the detection

Good question. I'm not entirely sure. I'd imagine that they'd just follow standards as well, but you're right - they seem to catch everything.

I think we could consider just attaching to every `text`/`password`/`email`/`tel`/`url` type input, but that'd mean a lot more breakage due to how we layout our button. We didn't want to inset it into the input like Lastpass does, for instance, but there's little else we can do while remaining noticeable and reachable for clicking. Then there's the issue of if every input is selected, what value to we map to them if a user chooses to **fill** the form? Submitting becomes even more difficult with multiple forms too, or if there even is a form 😅.

I think you get the point.. Haha. There's a lot going on here. I think to start with we just need to improve detection for inputs. Maybe we need to consider internationalisation for the input values too (names, classes) used in out [detection library](https://github.com/buttercup/locust).

**Comment by perry-mitchell** [comment]
I'll close this as it's a bit generic. If someone comes up with a better way to handle this, please post over at buttercup/locust.
