### ISSUE TITLE
OTP (2FA) auto-fill support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#268]
Detect OTP (2FA) fields on pages and provide support for autofilling them using OTP fields.

May depend on https://github.com/buttercup/locust/issues/34

**Comment by Hideman85** [comment]
I think a good start would be to show the OTP in the box since we have it in the config (entered manually)
![image](https://user-images.githubusercontent.com/16165119/98090128-8a989c00-1e7b-11eb-8845-653e513eb580.png)
![image](https://user-images.githubusercontent.com/16165119/98089758-1eb63380-1e7b-11eb-86b1-32d2782f5f4e.png)

**Comment by Hideman85** [comment]
Please give me an update, could we have at least the OTP on the Dropdown? :pray:

**Comment by Hideman85** [comment]
Any new on this? Could it be displayed **at least** under the dropdown?
It is very, very annoying to click on the dropdown, then click on vaults, then click on your vault, then click on your folder, then find your item, then click on it and then click on copy the code....
Please consider adding some priority on the mid-goal solution, that would help a lot already :pray:

**Comment by casasfernando** [comment]
@perry-mitchell I would love to see this implemented as well. At least to have the OTP in the extension dropdown as mentioned by @Hideman85.
I'm using MFA with OTP on every site that allows it, but it really slow me down to have to open Buttercup on the phone or desktop app to be able to get the OTP code. Having the code in the dropdown as we have the username or password would be really useful.

Thanks

**Comment by Hideman85** [comment]
Yes that is really a shame, I've been using the workaround for a year and I agree it is really annoying.
The feature already exist since in the vault we see the OTP realtime, so lets just have this in the dropdown as well.
Maybe auto-fill could for later but the dropdown is really value added, please really consider this 🙏

**Comment by perry-mitchell** [comment]
Sorry for the delay here - this is currently implemented in the upcoming release for the extension. It's close to being finished.

Once released a _lot_ will change in the extension, and it will include better OTP support.

**Comment by casasfernando** [comment]
Amazing news @perry-mitchell!
Looking forward the update. 👏

**Comment by perry-mitchell** [comment]
Done in V3.
