### ISSUE TITLE
ENHANCEMENT: Vault Interface to Web App

### ISSUE THREAD

**Issue by bigalgeorge** [buttercup/buttercup-browser-extension#284]
Since vault needs to be opened by extension, its logical the web interface be expanded to include such functions as full search, edit fields, multiselect fields for move/deletion etc, export/import and so on, doing away with the buttercup application. If others concur, perhaps add their pennyworth here as well thanks a lot.

 (google 'alistair george nz programmer'). I dont program any more due health but if you would like, I would be happy to put together a helpfile/methods suggestion for intended web app, if that may help.

**Comment by ldexterldesign** [comment]
I think the plan is to make Buttercup a manager for all [t]ypes (excuse pun) of private data not just web credentials. Based on this one could argue a desktop app makes sense.

FYI before I migrated to Buttercup, [D]ashlane, my previous private data manager, was in the process of migrating from desktop app to (extension-based) web app; I suspect because it suited their subscription payment model.

Technically there may be a plethora of answers such as  I'm sure Buttercup devs will elaborate in due course

Regards

Disclaimer: I generally prefer web apps over desktop apps

t: https://github.com/buttercup/buttercup-desktop/issues/540

**Comment by perry-mitchell** [comment]
Perhaps I'm completely misunderstanding the request (apologies if I am!) - I re-read this issue and the last twice, but I can't get my head around exactly what you're after. We have a vault interface in the extension **now**:

![image](https://user-images.githubusercontent.com/3869469/66700615-2bf60280-ecfb-11e9-9416-6fc8f88358b7.png)

Which can be opened by going through the menu:

![image](https://user-images.githubusercontent.com/3869469/66700631-59db4700-ecfb-11e9-805a-19337e9aa613.png)

Through this interface you can edit, search etc.. I'll readily admit that it's maybe not the easiest to find. Is that what you mean? 😅

**Comment by bigalgeorge** [comment]
Yes that is what I mean BUT unless Im having a bad head day, the only search within the web interface is a filter which actually is not a search at all please read my OP below:
//its logical the web interface be expanded to include such functions as full search, edit fields, multiselect fields for move/deletion etc, export/import and so on, doing away with the buttercup application. 
Granted, edit fields works, but there could be enhancements to that as well.

**Comment by bigalgeorge** [comment]
I think the search you are referring to is in the browser extension, not the web app; you need both.

**Comment by bigalgeorge** [comment]
Still referring to the web interface; consider the root folder (optionally) could include the contents of all the folders below as well? Reasoning being alphabetized full contents helps editing. However, if doing so, I recommend it is only optional; not fixed. EG checkbox under GROUPS [x] Global Root

**Comment by perry-mitchell** [comment]
Thanks for clarifying, though I feel I’m still missing some subtleties. For me the term web app is confusing as really everything we have besides the mobile app are web apps. We have the desktop application and this, the extension, but I’m not sure distinguishing which is which is important here - we’re taking about the browser extension and I’m not entirely sure what’s being asked for.

We have the vault mgmt interface in the extension so that using the desktop application isn’t necessary. Search is an aspect of both platforms and one we’re intending on improving- to my recollection the desktop is already using fuzzy search, albeit a more generic one. I agree with angling the one in this extension more towards urls as that’s what you’re really doing in the browser.

If the difference in features comes down to import/export and improved search, perhaps it’s better if we separate those into separate issues instead of aggregating them here? If I’ve missed something else forgive me, it’s late and I’ve been passing issues for a while now 😅

**Comment by bigalgeorge** [comment]
Thanks your reply what Im referring to as 'web app' is the form thats instantiated when you click on the browser extension/vaultname (unlocked)

**Comment by perry-mitchell** [comment]
> the root folder (optionally) could include the contents of all the folders below as well

Well the root folder/node is not selectable, which I prefer - it'd be out of place having a single root node always visible in my opinion. We will definitely work in something with the search field though, so that all entries might be shown once it's selected.

**Comment by perry-mitchell** [comment]
@bigalgeorge Thanks for the clarification. I'll address your points in more detail:

> full search

Planned, that's a must for us!

> edit fields

Already possible.

> multiselect fields for move/deletion etc

Great idea!

> export/import

Possible, but tricky. Not sure how easy this is when our importer is not designed for the browser. It uses hardcore OS-level crypto in some regards that can't currently be ported to the browser without substantial work. I'll leave this one in discussion for now.

> the url field should have priority

As mentioned in my last comment, I agree here. Definitely makes sense for a browser extension.

I'll go through and match up issues.

**Comment by perry-mitchell** [comment]
Searching: https://github.com/buttercup/ui/issues/24
Multi-select: https://github.com/buttercup/ui/issues/25

Currently the entire vault UI used here is housed over at this repo: https://github.com/buttercup/ui

It will soon be introduced to the desktop app, so work done there will be reflected on multiple platforms.

I'll close this as I feel that directing these ideas into individual issues will make the work more approachable. If you come up with more, please don't hesitate to create them here (if browser-only) or in the UI repo (for generic platform features). Thanks!

**Comment by ldexterldesign** [comment]
Glad I interjected - I did not know the desktop app was superfluous

Will explore the browser extension more and look forward to the update

Cheers
