### ISSUE TITLE
Local file source consolidated issue

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-browser-extension#362]
There are a number of ongoing issues with the local file datasource having intermittent failures with users. Neither @sallar nor myself have been able to reproduce the issue, so we're requesting debugging help from anyone willing to provide it.

Linked issues:
 * #282
 * #353

Topics:
 * [`Failed adding new entry: Failed writing remote file`](https://github.com/buttercup/buttercup-browser-extension/issues/282#issuecomment-546305427)
 * [Full error traces](https://github.com/buttercup/buttercup-browser-extension/issues/282#issuecomment-535777476)
 * [Debugging the local file host key](https://github.com/buttercup/buttercup-browser-extension/issues/282#issuecomment-573218462)
 * [Test vault with possible corruption](https://github.com/buttercup/buttercup-browser-extension/issues/282#issuecomment-580682872)
 * [Payload is too large](https://github.com/buttercup/buttercup-browser-extension/issues/282#issuecomment-651224546)

_Please do not open new issues for this problem, or instability relating to the use of the local file datasource._

**Comment by koenr** [comment]
Sorry, with the move of the issues, I don't know where or what to reply any more, so here then.
For me the issue is not fixed. I have to add that I have build my initial vault by importing an export from my Google passwords. That worked flawless and as I mentioned earlier: reading is no problem, only adding with the Firefox plugin (didn't try chrome yet).
Adding with the desktop app works.
As for the version: I don't think I have used a plugin version earlier then 2.20.2.
As for saving the vault again to make it shrink: it's not possible with the plugin, because that is the problem, so I added an item using the desktop version. The size of the vault went up from 1.7 to 1.9 MB by adding one name, userename and password. So it did not shrink. Version is 1.20.4
I know it is very frustrating not to be able to reproduce this problem and by the nature of the contents of the vaults if is of course not possible to send faulty vaults around :-(. But there is still something wrong here. If I can do something to help, please ask - I would very much like to see this solved, because I really like your software.

**Comment by patrick-motard** [comment]
I'm having the same issue. 

### OSX desktop version:

 Version 1.20.5 (1.20.5)

### Firefox plugin: 
Version
    2.24.1
Browser
    name: Firefox
    version: 85
    fullVersion: 85.0
    os: OS X
    
    
My local file vault was created by importing a lastpass csv. I have run through these steps with the vault located in both a documents folder, and in a nextcloud folder. Same issue in both locations. The steps followed:

- open the desktop app
- in the desktop app, unlock the vault
- in firefox, open the bcup extension, add the vault, using local file option, and the desktop app verification code
- try to log in to site with a password already stored in the vault, this works
- log in to account by entering credentials manually
- try to save the password to the bcup vault via the firefox extension

Results in red popup with the error:
```
 Failed saving credentials
Failed adding new entry: Failed writing remote file: redacted.bcup
```

This happens 100% of the time.
