### ISSUE TITLE
Failed unlocking source: Failed fetching Google Drive vault: n.refreshToken is not a function

### ISSUE THREAD

**Issue by llcoolju** [buttercup/buttercup-browser-extension#366]
Since the 2.21.0 update I get this error message when I try to unlock every single vault hosted on Google Drive :

> Failed unlocking archive
> Unable to unlock archive (xxxxx): Unlocking archive source (xxxxx) failed: Failed unlocking source: Failed fetching Google Drive vault: n.refreshToken is not a function

Browser : Chromium 
OS : MacOS

**Comment by lucasburlingham** [comment]
I have the same problem on Google Chrome, and this problem has only been around since the latest update (2.21.0 - 08/31/2020)

**Specs:**

5.0.4183.83 (Official Build) (64-bit)
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
OS | Linux (Ubuntu 20.04 running GNOME 3.36)
JavaScript | V8 8.5.210.20

I have tried to resolve this issue by removing the archive and then adding it again with the same details.
![image](https://user-images.githubusercontent.com/41302403/91782256-942b2c80-ebca-11ea-937d-317851c29755.png)

I have noticed that there is not an issue on the Buttercup Desktop version (Again, I am running Ubuntu 20.04, see neofetch output: 
![image](https://user-images.githubusercontent.com/41302403/91782385-e1a79980-ebca-11ea-9250-3176258780dc.png).

**Comment by anataty** [comment]
Hi, got this problem since 2.21.0 version.
Browser: Mozilla Firefox for Manjaro, Version 79.0 (64-bit)
OS: Manjaro Linux, 64-bit, GNOME version 3.36.5

**Comment by Gkupce** [comment]
I too am having this problem, for now I found that removing the vault from the chrome extension, and re-adding it serves as a workaround, but it is definitely not ideal.

**Comment by rafaelsza** [comment]
I'm also having the problem, using Google Chrome on Windows 10 PRO 64-bits, I can only access it if I remove the safe and add it again, it seems to be a problem with one of the extension's methods.

**Comment by perry-mitchell** [comment]
Most likely an API change here: https://github.com/buttercup/buttercup-browser-extension/blob/4a07ebe250bcc02586312b798f3f44a517175d65/source/background/library/googleDrive.js#L67

Whereas in the latest Google Drive client it's: https://github.com/buttercup/google-oauth2-client/blob/master/source/OAuth2Client.js#L79

I'd thought that our client had always been similar in terms of API with regards to the original Google OAuth2 client, but seems not. This should be an easy fix - Happy to accept a PR or I can look at it later today.

**Comment by iconhouse** [comment]
Any updates on when it might be fixed?
It updated again today but I can't use it with a failed fetch google drive error.
I tried **rafaelsza** method but restarting browser resets error again.
Now I am using desktop version. 
BTW, thank you for having desktop version.

**Comment by denali1** [comment]
This also occurs on Microsoft Edge Chromium Dev.

Microsoft Edge is up to date.
Version 86.0.622.3 (Official build) dev (64-bit)

**Comment by perry-mitchell** [comment]
Fixed - I'll release this very shortly (this evening).

**Comment by carboncls** [comment]
I just encountered this issue again.
Browser: Brave
MacOS

**Comment by caverna** [comment]
and now for a couple days again... :-(

**Comment by rafciozarzecz** [comment]
> and now for a couple days again... :-(

I logged out from all google accounts in the default browser and it helps, but I'm not sure for how long...

**Comment by abashtovyigeniusee** [comment]
I experience the same issue these couple of days
