### ISSUE TITLE
Failed connecting local vault | Edge

### ISSUE THREAD

**Issue by cptduffs** [buttercup/buttercup-browser-extension#460]
When trying to add a vault from Local File, I get the following error after clicking "Connect t oDesktop":
Failed connecting local vault
An error occurred when connecting: Failed to fetch.

I have the Desktop app open and unlocked, secure access is enabled. The extension works for Chrome, but not Edge.

**Comment by cptduffs** [comment]
I did some more testing, I got it to work when I created a new Edge profile. 
It doesn't work when I'm using my Work profile though, which is what I'm trying to do.

**Comment by Zeo070** [comment]
My suggestion is about your reviews on chrome extension 
Do you know that high number of reviews on chrome webstore would make The extension more visible on google search engine? Am here to elevate your extension to become more visible to the whole world.
    I specialise in giving positive reviews and also promoting legit extension to get more visibility in chrome webstore.
PLEASE I DON'T ENGAGE IN BOT DOWNLOADS OR Counterfeit Survey Because of THE CHROME extension guidelines and it will performance

So we spotlight on veritable and genuine techniques

TO TEST THE EFFICIENCY OF MY SERVICE WE CAN GO

FOR 30-100 reviews within 3-10 days

NOTE: I'M OFFERING POSITIVE REVIEWS 

Are you ready for these Offer??

**Comment by perry-mitchell** [comment]
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.
