### ISSUE TITLE
URI Malformed if Own/Nextcloud is a root domain

### ISSUE THREAD

**Issue by doodlemania2** [buttercup/buttercup-browser-extension#71]
Nextcloud installed at root domain (https://mycloud.com) and attempting to use that as the root for my passwords. Getting URI malformed when attempting to create or use existing archive.

**Comment by perry-mitchell** [comment]
Hi @doodlemania2 - We haven't seen this issue yet, and were mainly testing against the [Nextcloud demo server](https://demo.nextcloud.com/).

Would you be able to try and help us narrow down the issue? Could you try, for instance:

1. Using `https://mycloud.com/` (notice the trailing slash)
2. Trying a demo account at [https://demo.nextcloud.com/](https://demo.nextcloud.com/)
3. Trying a sub folder in your account

The answers to these might help us look in the right direction.

**Comment by doodlemania2** [comment]
Thanks for reaching out to me.
So I tried the trailing slash.
Tried the subfolder (attempted to Create in documents folder)
Also tried to open an existing one (used the desktop app to create one and uploaded it)
All of the above gave me URI malformed.

Oddly, tried https://demo.nextcloud.com/test04 (random one I just created) and got a 503 from plugin.

Is there a debug flag I can set on the extension that can give us a bit more info? Happy to help test with you!

**Comment by perry-mitchell** [comment]
Thank you for taking the time to lodge an issue - let's hope we can solve it.

There's no debug flag but you can use the devtools to help find the issue. For instance, the setup pages where you add the archive will show some basic UI stuff:

![image](https://cloud.githubusercontent.com/assets/3869469/26558230/de29e1e8-44af-11e7-8f75-ceebbbef50b3.png)

(or not) my bet is on the background tab. If you go into chrome extensions (I'm assuming nothing of course, apologies if you're familiar):

![image](https://cloud.githubusercontent.com/assets/3869469/26558259/0d4c69fa-44b0-11e7-9201-70748d68e0f7.png)

You can inspect the background page by clicking the link:

![image](https://cloud.githubusercontent.com/assets/3869469/26558282/26dc28a6-44b0-11e7-8144-1cede2fdddc3.png)

![image](https://cloud.githubusercontent.com/assets/3869469/26558291/3548c566-44b0-11e7-8e0c-2a2f4e329b72.png)

If you keep it open **before and during** you trying to connect, you should have some interesting stuff in the network panel. If you could right-click and save as a HAR and send it here that would really help (making sure you snip any passwords/credentials/URLs in there before!). If you don't want to paste it here you can send it to us privately at info@buttercup.pw.

Would this be alright?

**Comment by perry-mitchell** [comment]
> Oddly, tried https://demo.nextcloud.com/test04 (random one I just created) and got a 503 from plugin.

Unfortunately that 503 is something @sallar and I were getting some time ago. Hopefully it stops coming (could be an issue with the demo stack perhaps).

**Comment by doodlemania2** [comment]
Hi there - sorry for the delay. Not sure if I caught what we're wanting to catch but here's a screenshot of the extension watching:
![image](https://cloud.githubusercontent.com/assets/5252217/26612653/d104dd20-457b-11e7-99f8-fd5054f8c7c1.png)
This route didn't record any network traffic...but....

Here's a file that I was able to gather in another view (I opened the developer tools on the chrome tab itself once I clicked Add Archive.

[heflipieckodmcppbnembejjmabajjjj.zip](https://github.com/buttercup/buttercup-browser-extension/files/1040129/heflipieckodmcppbnembejjmabajjjj.zip)
This caught some network traffic to webdav, mostly listing out folder structure and such which did succeed. After I entered my info though, same URI malformed error.

(the word "redacted" is in place of my actual URI).

**Comment by perry-mitchell** [comment]
Hi @doodlemania2 - I removed the linked file because it still contained your auth information in base64. Remember to check the headers when redacting a HAR file.. but perhaps next time we'll just get everyone to email them as it's a bit safer.

Regarding the contents - Due to the error it may be that no request is made at all. Let's try something else then. I'll try to make a failing test case in our core webdav libraries with a root domain and will get back to you.

**Comment by doodlemania2** [comment]
Thanks for that - fortunately, is a throw away cred!

**Comment by perry-mitchell** [comment]
Hi @doodlemania2 - Unfortunately I wasn't able to locate the source of the issue, playing around with pathing in the extension. Without an easier way to reproduce, I'm afraid that this issue is blocked by the following items:

 * Issue perry-mitchell/webdav-client#27 which involves creating a test server (allows us to test root domains like yours)
 * Issue perry-mitchell/webdav-client#28 which involves writing tests

If there's any other info/updates please send them through. We're quite busy but we'll hopefully get to them soon. If you want to have a crack at trying to debug further I would recommend placing breakpoints until you find something weird (or somewhere that shows parts of the URL being joined), and screenshot that for this issue.

**Comment by doodlemania2** [comment]
I'd be happy to grant you access to my Nextcloud instance for a few days to work on it. I don't have Chrome dev experience so not sure how to help debug. Let me know or reach out to me offline. I'm on KeyBase, Signal, etc :)

**Comment by perry-mitchell** [comment]
That would actually work very well for solving this. Perhaps you could grant me a limited account for a few days to test against? I'm on keybase as **perrymitchell** if you'd like to send credentials.

I'm hoping the issue is just in the browser extension and not the webdav-fs library in the core, otherwise updating each project could take some days. Let's see :)

**Comment by doodlemania2** [comment]
Connected with you via Keybase!

**Comment by perry-mitchell** [comment]
Thanks heaps for the effort @doodlemania2 - Makes it so much easier.

So first off I tried connecting with the provided credentials using **ownCloud**, which worked:

![image](https://cloud.githubusercontent.com/assets/3869469/26762875/3ae9818a-4952-11e7-97f6-140285db5abb.png)

And then, as described, I get the error:

![image](https://cloud.githubusercontent.com/assets/3869469/26762882/5f747a5a-4952-11e7-8203-3e9dca356975.png)

Traced the formation of the URL to an old version of our webdav library:

![image](https://cloud.githubusercontent.com/assets/3869469/26762895/b067a43c-4952-11e7-9eed-20f636192373.png)

I'll continue working with this, but so far we have a suspect 🙂

**Comment by perry-mitchell** [comment]
@doodlemania2 I got this weird error when trying the same request from postman:

![image](https://cloud.githubusercontent.com/assets/3869469/26763106/93035320-4955-11e7-8ad5-c4c0fe635321.png)

I'm trying to HTTP PUT to `https://myUsername:myPassword@yourwebsite.com/remote.php/webdav/Documents/test.bcup` and getting a 503 Service Unavailable error..

**Comment by perry-mitchell** [comment]
Ah! It might be the password! The old version of WebDAV may be the culprit. @doodlemania2 could you please change my pass to something simple (to test).. perhaps just letters and numbers? No punctuation?

If it is what I think it is, we need to upgrade the webdav library to using header authentication rather than embedded. If this is the case it could still be another few days out as it's a larger update.

**Comment by perry-mitchell** [comment]
@doodlemania2 Slowly moving through it. I apologies for the wait. It'll be still a couple of days maybe until I finish the update. Unfortunately we'd delayed a bit of necessary work to include the upgrade so we have to tackle that debt now.

**Comment by perry-mitchell** [comment]
Ok.. So I think I cracked it. Release is coming - 0.14.0. Please wait for that and let me know if the update worked 😊

Thanks for the help!
