### ISSUE TITLE
[Enhancement] Unlock automatically

### ISSUE THREAD

**Issue by simonbcn** [buttercup/buttercup-browser-extension#78]
When I open Firefox, the extension is locked. The security is good but in my personal computer (_in my home_) isn't necessary. The current behavior is annoying. I should be able to decide to automatically unlock the database.

**Comment by perry-mitchell** [comment]
So there's a couple of aspects to this request. The first one is technical: **how** would we unlock automatically without sacrificing security? We can't encrypt and store their master password because any key we used for that would be exposed one way or another. Also, allowing people to use weaker security options is, in my opinion, a bad idea as laziness trumps good will. I think that allowing weakened security measures at all will mean more security holes overall, and that's not a direction we want for this product.

Second aspect is that I don't know that many other password managers allow for this functionality. For example, lastpass prompts for login information after being reopened (or at least did in my experience) (may have been 2 factor only). As we don't have 2 factor yet we rely on the master password.

**Comment by simonbcn** [comment]
Actually I'm using bitwarden and it does this.

**Comment by perry-mitchell** [comment]
Ok so looking through their source code I haven't yet found anything that would show me how they keep it unlocked between sessions apart from their use of the [chrome storage api](https://github.com/bitwarden/browser/blob/master/src/services/userService.js#L31). It looks like they're writing raw credentials and everything else [to the storage](https://github.com/bitwarden/browser/search?utf8=%E2%9C%93&q=chrome.storage.local.&type=). It also seems that they're writing some kind of [encryption keys to the storage](https://github.com/bitwarden/browser/search?utf8=%E2%9C%93&q=.+setEncKey&type=) as well.

I'm not sure if it is like I've found, and would appreciate any links to the source that indicate otherwise. I'll give them the benefit of the doubt that they're not just writing the key to the storage.
